---
http_interactions:
- request:
    method: get
    uri: http://addressfacade.cloudapp.net/address-service/v1/addresses/77138?client-id=example%20team1&key=clientduffnaff
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - "*/*; q=0.5, application/xml"
      Accept-Encoding:
      - gzip, deflate
      User-Agent:
      - Ruby
  response:
    status:
      code: 401
      message: Unauthorized
    headers:
      Date:
      - Fri, 11 Dec 2015 13:01:10 GMT
      Content-Length:
      - '0'
    body:
      encoding: UTF-8
      string: ''
    http_version:
  recorded_at: Fri, 11 Dec 2015 13:00:50 GMT
recorded_with: VCR 3.0.0
